solr:
  image: liwang0513/solr
  imageTag: latest
  imagePullPolicy: "Always"
  storageClass: standard
  master:
    persistence:
      diskSize: 2Gi
    resources: {}
  slave:
    persistence:
      diskSize: 2Gi
    resources: {}

service:
  type: ClusterIP
