apiVersion: v1
kind: Service
metadata:
  labels:
    component: solr
    solr-role: slave
  name: {{ .Release.Name }}-solr-slave
  namespace: default
spec:
  ports:
  - name: solr-container
    port: 8983
    protocol: TCP
    targetPort: 8983
  selector:
    component: solr
    solr-role: slave
  sessionAffinity: None
  type: ClusterIP
